userena/contrib/umessages/urls.py
from django.conf.urls import *
from userena.contrib.umessages import views as messages_views
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^compose/$',
        messages_views.message_compose,
        name='userena_umessages_compose'),

    url(r'^compose/(?P<recipients>[\+\.\w]+)/$',
        messages_views.message_compose,
        name='userena_umessages_compose_to'),

    url(r'^reply/(?P<parent_id>[\d]+)/$',
        messages_views.message_compose,
        name='userena_umessages_reply'),

    url(r'^view/(?P<username>[\.\w]+)/$',
        login_required(messages_views.MessageDetailListView.as_view()),
        name='userena_umessages_detail'),

    url(r'^remove/$',
        messages_views.message_remove,
        name='userena_umessages_remove'),

    url(r'^unremove/$',
        messages_views.message_remove,
        {'undo': True},
        name='userena_umessages_unremove'),

    url(r'^$',
        login_required(messages_views.MessageListView.as_view()),
        name='userena_umessages_list'),
)

userena/contrib/umessages/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from userena.utils import truncate_words
from userena.contrib.umessages.managers import (MessageManager, MessageContactManager,
                                                MessageRecipientManager)
from userena.utils import user_model_label


@python_2_unicode_compatible
class MessageContact(models.Model):
    """
    Contact model.

    A contact is a user to whom a user has send a message to or
    received a message from.

    """
    um_from_user = models.ForeignKey(user_model_label, verbose_name=_("from user"),
                                  related_name=('um_from_users'))

    um_to_user = models.ForeignKey(user_model_label, verbose_name=_("to user"),
                                related_name=('um_to_users'))

    latest_message = models.ForeignKey('Message',
                                       verbose_name=_("latest message"))

    objects = MessageContactManager()

    class Meta:
        unique_together = ('um_from_user', 'um_to_user')
        ordering = ['latest_message']
        verbose_name = _("contact")
        verbose_name_plural = _("contacts")

    def __str__(self):
        return (_("%(um_from_user)s and %(um_to_user)s")
                % {'um_from_user': self.um_from_user.username,
                   'um_to_user': self.um_to_user.username})

    def opposite_user(self, user):
        """
        Returns the user opposite of the user that is given

        :param user:
            A Django :class:`User`.

        :return:
            A Django :class:`User`.

        """
        if self.um_from_user == user:
            return self.um_to_user
        else: return self.um_from_user


@python_2_unicode_compatible
class MessageRecipient(models.Model):
    """
    Intermediate model to allow per recipient marking as
    deleted, read etc. of a message.

    """
    user = models.ForeignKey(user_model_label,
                             verbose_name=_("recipient"))

    message = models.ForeignKey('Message',
                                verbose_name=_("message"))

    read_at = models.DateTimeField(_("read at"),
                                   null=True,
                                   blank=True)

    deleted_at = models.DateTimeField(_("recipient deleted at"),
                                      null=True,
                                      blank=True)

    objects = MessageRecipientManager()

    class Meta:
        verbose_name = _("recipient")
        verbose_name_plural = _("recipients")

    def __str__(self):
        return (_("%(message)s")
                % {'message': self.message})

    def is_read(self):
        """ Returns a boolean whether the recipient has read the message """
        return self.read_at is None


@python_2_unicode_compatible
class Message(models.Model):
    """ Private message model, from user to user(s) """
    body = models.TextField(_("body"))

    sender = models.ForeignKey(user_model_label,
                               related_name='sent_messages',
                               verbose_name=_("sender"))

    recipients = models.ManyToManyField(user_model_label,
                                        through='MessageRecipient',
                                        related_name="received_messages",
                                        verbose_name=_("recipients"))

    sent_at = models.DateTimeField(_("sent at"),
                                   auto_now_add=True)

    sender_deleted_at = models.DateTimeField(_("sender deleted at"),
                                             null=True,
                                             blank=True)

    objects = MessageManager()

    class Meta:
        ordering = ['-sent_at']
        verbose_name = _("message")
        verbose_name_plural = _("messages")

    def __str__(self):
        """ Human representation, displaying first ten words of the body. """
        truncated_body = truncate_words(self.body, 10)
        return "%(truncated_body)s" % {'truncated_body': truncated_body}

    def save_recipients(self, um_to_user_list):
        """
        Save the recipients for this message

        :param um_to_user_list:
            A list which elements are :class:`User` to whom the message is for.

        :return:
            Boolean indicating if any users are saved.

        """
        created = False
        for user in um_to_user_list:
            MessageRecipient.objects.create(user=user,
                                            message=self)
            created = True
        return created

    def update_contacts(self, um_to_user_list):
        """
        Updates the contacts that are used for this message.

        :param um_to_user_list:
            List of Django :class:`User`.

        :return:
            A boolean if a user is contact is updated.

        """
        updated = False
        for user in um_to_user_list:
            MessageContact.objects.update_contact(self.sender,
                                                  user,
                                                  self)
            updated = True
        return updated

userena/contrib/umessages/templates/umessages/base_message.html
{% extends "base.html" %}

userena/contrib/umessages/templates/umessages/message_detail.html
{% extends 'umessages/base_message.html' %}
{% load i18n %}

{% block content_title %}<h2>{% blocktrans %}Conversation with {{ recipient }}{% endblocktrans %}</h2>{% endblock %}

{% block content %}

<ul>
{% for message in message_list %}
<li>
  {{ message }}
  <p>{% blocktrans with message.sent_at as sent_at %}Received on {{ sent_at }}{% endblocktrans %}</p>
</li>
{% endfor %}
</ul>
{% endblock %}

userena/contrib/umessages/templates/umessages/message_form.html
{% extends 'umessages/base_message.html' %}
{% load i18n %}

{% block content_title %}<h2>{% trans "Compose" %}</h2>{% endblock %}

{% block content %}
<form action="" method="post" id="compose_message_form">
  {% csrf_token %}
  <fieldset>
    <legend>{% trans "Compose message" %}</legend>
    {{ form.as_p }}
  </fieldset>
  <input type="submit" name="send" value="{% trans "Send" %}" />
</form>
{% endblock %}

userena/contrib/umessages/templates/umessages/message_list.html
{% extends 'umessages/base_message.html' %}
{% load i18n umessages_tags %}
{% load url from future %}

{% block content_title %}<h2>{% trans "Messages" %}</h2>{% endblock %}

{% block content %}
{% get_unread_message_count_for user as unread_message_count %}
{% blocktrans %}{{ unread_message_count }} new messages.{% endblocktrans %}
<a href="{% url 'userena_umessages_compose' %}">{% trans "Compose" %}</a>
<ul>
  {% for message in message_list %}
  <li>
  {% if message.um_from_user == user %}
  <a href="{% url 'userena_umessages_detail' message.um_to_user.username %}">{{ message.um_to_user }}</a>
  {% get_unread_message_count_between user and message.um_to_user as unread_between_count %}
  {% else %}
  <a href="{% url 'userena_umessages_detail' message.um_from_user.username %}">{{ message.um_from_user }}</a>
  {% get_unread_message_count_between user and message.um_from_user as unread_between_count %}
  {% endif %}
  {% blocktrans with message.latest_message as latest_message %}{{ latest_message }} ({{ unread_between_count }} new){% endblocktrans %}
  </li>
  {% endfor %}
</ul>
{% endblock %}